[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  omit_hostname = false

[[outputs.influxdb_v2]]
  urls = ["http://influxdb3-core:8181"]
  token = "$INFLUXDB_TOKEN"
  organization = "Student"
  bucket = "factorydatabase"

[[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto:1883"]
  topics = ["fabrica/ativo/+"]
  data_format = "json_v2"
  username = ""
  password = ""
  tls_ca = ""
  tls_cert = ""
  tls_key = ""
  insecure_skip_verify = false

  [[inputs.mqtt_consumer.json_v2]]
    measurement_name = "fabrica_ativos"

    [[inputs.mqtt_consumer.json_v2.object]]
      path = "@this"
      tags = ["asset_id"]
      
      [[inputs.mqtt_consumer.json_v2.object.field]]
        path = "power_consumption_kw"
        type = "float"
      
      [[inputs.mqtt_consumer.json_v2.object.field]]
        path = "item_id"
        type = "string"
        optional = true
      
      [[inputs.mqtt_consumer.json_v2.object.field]]
        path = "cycle_time_for_this_item"
        type = "float"

      [[inputs.mqtt_consumer.json_v2.object.field]]
        path = "status"
        type = "string"

[[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto:1883"]
  topics = ["fabrica/processo/qualidade"]
  data_format = "json_v2"
  username = ""
  password = ""
  tls_ca = ""
  tls_cert = ""
  tls_key = ""
  insecure_skip_verify = false

  [[inputs.mqtt_consumer.json_v2]]
    measurement_name = "fabrica_qualidade"

    [[inputs.mqtt_consumer.json_v2.object]]
      path = "@this"
      tags = ["sensor_id", "reason_code"]
      
      [[inputs.mqtt_consumer.json_v2.object.field]]
        path = "item_id"
        type = "string"
        optional = true
      [[inputs.mqtt_consumer.json_v2.object.field]]
        path = "status"
        type = "string"

[[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto:1883"]
  topics = ["fabrica/itens"]
  data_format = "json_v2"
  username = ""
  password = ""
  tls_ca = ""
  tls_cert = ""
  tls_key = ""
  insecure_skip_verify = false

  [[inputs.mqtt_consumer.json_v2]]
    measurement_name = "fabrica_itens"

    [[inputs.mqtt_consumer.json_v2.object]]
      path = "@this"
      
      [[inputs.mqtt_consumer.json_v2.object.field]]
        path = "count"
        type = "int"
